services:
  backend:
    build:
      context: .
      dockerfile: ./be/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - ./be/.env
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./fe/Dockerfile          
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_OPENAI_API_KEY=${VITE_OPENAI_API_KEY}

    ports:
      - '5173:80'
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL","sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./be/db/objects/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    ports:
      - "5432:5432"
    expose:
      - "5432"

networks:
  app-network:
    driver: bridge

volumes:
  db-data: