import React from 'react';
import { Typography, Box, Container, Link, Button } from '@mui/material';
import { Link as RouterLink } from 'react-router-dom';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
const PoliticaPrivacidad = () => {
    const BotonVolver = () => (React.createElement(Button, { component: RouterLink, to: "/", startIcon: React.createElement(ArrowBackIcon, null), variant: "contained", sx: { mb: 2 } }, "Volver al Inicio"));
    return (React.createElement(Container, { maxWidth: "md" },
        React.createElement(Box, { my: 4 },
            React.createElement(BotonVolver, null),
            React.createElement(Typography, { variant: "h4", component: "h1", gutterBottom: true }, "Pol\u00EDtica de Privacidad de SuperAI Empresarial"),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "1. Introducci\u00F3n"),
            React.createElement(Typography, { paragraph: true }, "En SuperAI Empresarial, respetamos su privacidad y nos comprometemos a proteger su informaci\u00F3n personal. Esta pol\u00EDtica de privacidad describe c\u00F3mo recopilamos, usamos, divulgamos y protegemos su informaci\u00F3n cuando utiliza nuestros servicios."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "2. Informaci\u00F3n que Recopilamos"),
            React.createElement(Typography, { paragraph: true }, "Podemos recopilar y procesar la siguiente informaci\u00F3n personal:"),
            React.createElement(Typography, { component: "ul" },
                React.createElement("li", null, "Informaci\u00F3n de Contacto: Nombre, direcci\u00F3n de correo electr\u00F3nico, n\u00FAmero de tel\u00E9fono y direcci\u00F3n f\u00EDsica."),
                React.createElement("li", null, "Informaci\u00F3n de Cuenta: Nombre de usuario, contrase\u00F1a y detalles de la cuenta."),
                React.createElement("li", null, "Datos de Uso: Informaci\u00F3n sobre c\u00F3mo interact\u00FAa con nuestro servicio, incluyendo direcciones IP, tipo de navegador, p\u00E1ginas visitadas, tiempo en cada p\u00E1gina y acciones realizadas."),
                React.createElement("li", null, "Datos Transaccionales: Detalles de pagos y transacciones realizadas a trav\u00E9s de nuestros servicios.")),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "3. Uso de la Informaci\u00F3n"),
            React.createElement(Typography, { paragraph: true }, "Utilizamos la informaci\u00F3n recopilada para:"),
            React.createElement(Typography, { component: "ul" },
                React.createElement("li", null, "Proveer y Mejorar Servicios: Administrar su cuenta, proporcionar nuestros servicios y mejorar su experiencia de usuario."),
                React.createElement("li", null, "Comunicaciones: Enviar notificaciones, actualizaciones y otra informaci\u00F3n relevante sobre nuestros servicios."),
                React.createElement("li", null, "Marketing: Enviar materiales promocionales, ofertas especiales y otra informaci\u00F3n que pueda ser de su inter\u00E9s, siempre y cuando haya dado su consentimiento para recibir estas comunicaciones."),
                React.createElement("li", null, "Seguridad: Proteger la integridad y seguridad de nuestros servicios y prevenir fraudes."),
                React.createElement("li", null, "Cumplimiento Legal: Cumplir con nuestras obligaciones legales y regulatorias.")),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "4. Compartir Informaci\u00F3n"),
            React.createElement(Typography, { paragraph: true }, "No compartimos su informaci\u00F3n personal con terceros, excepto en los siguientes casos:"),
            React.createElement(Typography, { component: "ul" },
                React.createElement("li", null, "Proveedores de Servicios: Podemos compartir su informaci\u00F3n con proveedores de servicios de confianza que nos ayudan a operar y mejorar nuestro servicio."),
                React.createElement("li", null, "Cumplimiento Legal: Podemos divulgar su informaci\u00F3n para cumplir con leyes aplicables, regulaciones, procesos legales o solicitudes gubernamentales."),
                React.createElement("li", null, "Transferencias Comerciales: En caso de una fusi\u00F3n, adquisici\u00F3n o venta de activos, su informaci\u00F3n puede ser transferida como parte de esa transacci\u00F3n.")),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "5. Seguridad de la Informaci\u00F3n"),
            React.createElement(Typography, { paragraph: true }, "Implementamos medidas de seguridad t\u00E9cnicas y organizativas apropiadas para proteger su informaci\u00F3n personal contra p\u00E9rdida, uso indebido, acceso no autorizado, divulgaci\u00F3n, alteraci\u00F3n y destrucci\u00F3n. Sin embargo, ning\u00FAn sistema de seguridad es infalible, y no podemos garantizar la seguridad absoluta de su informaci\u00F3n."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "6. Retenci\u00F3n de Datos"),
            React.createElement(Typography, { paragraph: true }, "Retendremos su informaci\u00F3n personal solo durante el tiempo necesario para cumplir con los fines para los cuales fue recopilada, incluidos los fines de cumplir con cualquier requisito legal, contable o de informes."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "7. Sus Derechos"),
            React.createElement(Typography, { paragraph: true }, "Usted tiene derecho a:"),
            React.createElement(Typography, { component: "ul" },
                React.createElement("li", null, "Acceso: Solicitar una copia de la informaci\u00F3n personal que tenemos sobre usted."),
                React.createElement("li", null, "Rectificaci\u00F3n: Solicitar la correcci\u00F3n de cualquier informaci\u00F3n inexacta o incompleta."),
                React.createElement("li", null, "Eliminaci\u00F3n: Solicitar la eliminaci\u00F3n de su informaci\u00F3n personal cuando ya no sea necesaria para los fines para los que fue recopilada."),
                React.createElement("li", null, "Restricci\u00F3n: Solicitar la restricci\u00F3n del procesamiento de su informaci\u00F3n personal en ciertas circunstancias."),
                React.createElement("li", null, "Portabilidad: Solicitar que le proporcionemos su informaci\u00F3n personal en un formato estructurado, de uso com\u00FAn y legible por m\u00E1quina.")),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "8. Cookies y Tecnolog\u00EDas Similares"),
            React.createElement(Typography, { paragraph: true }, "Utilizamos cookies y tecnolog\u00EDas similares para recopilar datos sobre su uso de nuestro servicio y para mejorar su experiencia en l\u00EDnea. Puede configurar su navegador para rechazar todas o algunas cookies, o para alertarlo cuando se env\u00EDen cookies."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "9. Cambios a esta Pol\u00EDtica de Privacidad"),
            React.createElement(Typography, { paragraph: true }, "Podemos actualizar esta pol\u00EDtica de privacidad de vez en cuando. Cualquier cambio se publicar\u00E1 en esta p\u00E1gina con una fecha de revisi\u00F3n actualizada. Le recomendamos que revise esta pol\u00EDtica peri\u00F3dicamente para estar informado sobre c\u00F3mo protegemos su informaci\u00F3n."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "10. Contacto"),
            React.createElement(Typography, { paragraph: true }, "Si tiene alguna pregunta o inquietud sobre esta pol\u00EDtica de privacidad o sobre nuestras pr\u00E1cticas de privacidad, cont\u00E1ctenos en:"),
            React.createElement(Typography, { component: "ul" },
                React.createElement("li", null,
                    "Correo Electr\u00F3nico: ",
                    React.createElement(Link, { href: "mailto:chelo@ai4u.com.co" }, "chelo@ai4u.com.co")),
                React.createElement("li", null, "Tel\u00E9fono: +57 321 817 5744")),
            React.createElement(Box, { mt: 4 },
                React.createElement(BotonVolver, null)))));
};
export default PoliticaPrivacidad;
