import React from 'react';
import { Typography, Box, Container, Link, Button } from '@mui/material';
import { Link as RouterLink } from 'react-router-dom';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
const TerminosYCondiciones = () => {
    const BotonVolver = () => (React.createElement(Button, { component: RouterLink, to: "/", startIcon: React.createElement(ArrowBackIcon, null), variant: "contained", sx: { mb: 2 } }, "Volver al Inicio"));
    return (React.createElement(Container, { maxWidth: "md" },
        React.createElement(Box, { my: 4 },
            React.createElement(BotonVolver, null),
            React.createElement(Typography, { variant: "h4", component: "h1", gutterBottom: true }, "T\u00E9rminos y Condiciones de SuperAI Empresarial"),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "1. Aceptaci\u00F3n de los T\u00E9rminos"),
            React.createElement(Typography, { paragraph: true }, "Al acceder y utilizar los servicios de SuperAI Empresarial, usted acepta cumplir y estar sujeto a los siguientes t\u00E9rminos y condiciones. Si no est\u00E1 de acuerdo con estos t\u00E9rminos, no utilice nuestros servicios."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "2. Descripci\u00F3n del Servicio"),
            React.createElement(Typography, { paragraph: true }, "SuperAI Empresarial proporciona soluciones de inteligencia artificial para empresas, incluyendo an\u00E1lisis predictivo, integraci\u00F3n de datos y optimizaci\u00F3n de procesos. Nos reservamos el derecho de modificar o descontinuar el servicio en cualquier momento sin previo aviso."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "3. Uso del Servicio"),
            React.createElement(Typography, { component: "div" },
                React.createElement("ul", null,
                    React.createElement("li", null,
                        React.createElement("strong", null, "Licencia:"),
                        " Le otorgamos una licencia limitada, no exclusiva, intransferible y revocable para utilizar nuestros servicios seg\u00FAn estos t\u00E9rminos."),
                    React.createElement("li", null,
                        React.createElement("strong", null, "Prohibiciones:"),
                        " No puede utilizar el servicio para actividades ilegales, infringir los derechos de otros, o interferir con la operatividad del servicio."))),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "4. Registro de Usuarios"),
            React.createElement(Typography, { paragraph: true }, "Para acceder a ciertas funcionalidades, puede ser necesario registrarse y crear una cuenta. Usted es responsable de mantener la confidencialidad de su informaci\u00F3n de cuenta y de todas las actividades que ocurran bajo su cuenta."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "5. Privacidad"),
            React.createElement(Typography, { paragraph: true },
                "Su privacidad es importante para nosotros. Por favor, revise nuestra ",
                React.createElement(Link, { href: "/politica-de-privacidad" }, "Pol\u00EDtica de Privacidad"),
                " para entender c\u00F3mo recopilamos, utilizamos y protegemos su informaci\u00F3n personal."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "6. Propiedad Intelectual"),
            React.createElement(Typography, { paragraph: true }, "Todos los contenidos y materiales disponibles en SuperAI Empresarial, incluyendo pero no limit\u00E1ndose a textos, gr\u00E1ficos, logotipos y software, son propiedad de la empresa o sus licenciantes y est\u00E1n protegidos por derechos de autor y otras leyes de propiedad intelectual."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "7. Limitaci\u00F3n de Responsabilidad"),
            React.createElement(Typography, { paragraph: true }, "En la m\u00E1xima medida permitida por la ley aplicable, SuperAI Empresarial no ser\u00E1 responsable de ning\u00FAn da\u00F1o indirecto, incidental, especial, consecuente o punitivo, ni de ninguna p\u00E9rdida de beneficios o ingresos, ya sea incurrida directa o indirectamente, o cualquier p\u00E9rdida de datos, uso, buena voluntad u otras p\u00E9rdidas intangibles, resultante de:"),
            React.createElement(Typography, { component: "div" },
                React.createElement("ul", null,
                    React.createElement("li", null, "Su acceso o uso o incapacidad para acceder o usar el servicio;"),
                    React.createElement("li", null, "Cualquier conducta o contenido de terceros en el servicio;"),
                    React.createElement("li", null, "Cualquier contenido obtenido del servicio; y"),
                    React.createElement("li", null, "Acceso, uso o alteraci\u00F3n no autorizados de sus transmisiones o contenido."))),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "8. Indemnizaci\u00F3n"),
            React.createElement(Typography, { paragraph: true }, "Usted se compromete a indemnizar y eximir de responsabilidad a SuperAI Empresarial y sus afiliados, directores, empleados y agentes de cualquier reclamo, p\u00E9rdida, da\u00F1o, responsabilidad y costo (incluidos los honorarios de abogados) que surjan de su uso del servicio, su violaci\u00F3n de estos t\u00E9rminos, o su violaci\u00F3n de cualquier derecho de un tercero."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "9. Modificaciones a los T\u00E9rminos"),
            React.createElement(Typography, { paragraph: true }, "Nos reservamos el derecho de modificar estos t\u00E9rminos en cualquier momento. Las modificaciones ser\u00E1n efectivas cuando se publiquen en nuestro sitio web. Su uso continuado del servicio despu\u00E9s de la publicaci\u00F3n de los t\u00E9rminos modificados constituir\u00E1 su aceptaci\u00F3n de dichos t\u00E9rminos."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "10. Terminaci\u00F3n"),
            React.createElement(Typography, { paragraph: true }, "Nos reservamos el derecho de suspender o terminar su acceso al servicio en cualquier momento, sin previo aviso y por cualquier motivo, incluyendo el incumplimiento de estos t\u00E9rminos."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "11. Ley Aplicable"),
            React.createElement(Typography, { paragraph: true }, "Estos t\u00E9rminos se regir\u00E1n e interpretar\u00E1n de acuerdo con las leyes del pa\u00EDs en el que se encuentra nuestra empresa, sin tener en cuenta los principios de conflictos de leyes."),
            React.createElement(Typography, { variant: "h6", component: "h2", gutterBottom: true }, "12. Contacto"),
            React.createElement(Typography, { paragraph: true },
                "Para cualquier pregunta sobre estos t\u00E9rminos, por favor cont\u00E1ctenos en ",
                React.createElement(Link, { href: "mailto:contacto@superai.com" }, "contacto@superai.com"),
                " o en nuestra direcci\u00F3n f\u00EDsica: Calle Ejemplo 123, Ciudad Ejemplo, Pa\u00EDs Ejemplo."),
            React.createElement(Box, { mt: 4 },
                React.createElement(BotonVolver, null)))));
};
export default TerminosYCondiciones;
